In [113]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
# Load the datasets
data1 = pd.read_csv('data1.csv')
data2 = pd.read_csv('data2.csv')
data3 = pd.read_csv('data3.csv')

In [88]:
# Merge data1 and data2 on the "Courier" column
merged_data = pd.merge(data1, data2, left_on='Courier', right_on='Courier', how='left')

# Merge the result with data3 on the "Weight Slab" column
merged_data = pd.merge(merged_data, data3, left_on='Weight Slab', right_on='Weight Slab', how='left')

In [89]:
merged_data

,AWB,Courier,Zone,Charged wt,Courier Slab,Multiplier,Direction,RateCard,Weight Slab,Additional,Ratecard 1,Freight Type,A,B,C,D,E
0,96403,Delhivery Surface 10 Kgs,A,10.5000,10.0,1,Forward,Ratecard 1,10.0,1.0,Forward,Base,₹ 128,₹ 148,₹ 207,₹ 255,₹ 297
1,96403,Delhivery Surface 10 Kgs,A,10.5000,10.0,1,Forward,Ratecard 1,10.0,1.0,Forward,Additional 1 kg,₹ 11,₹ 13,₹ 18,₹ 22,₹ 26
2,96403,Delhivery Surface 10 Kgs,A,10.5000,10.0,1,Forward,Ratecard 1,10.0,1.0,Return,Base,₹ 89.25,₹ 103.88,₹ 145.22,₹ 178.50,₹ 207.75
3,96403,Delhivery Surface 10 Kgs,A,10.5000,10.0,1,Forward,Ratecard 1,10.0,1.0,Return,Additional 1 kg,₹ 11.08,₹ 12.90,₹ 18.05,₹ 22.18,₹ 25.81
4,96404,Shipsy,A,0.5475,0.5,1,Forward,Ratecard 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198,96466,Shipsy,A,5.1750,0.5,10,Forward,Ratecard 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199,96467,Delhivery Surface,A,0.7500,0.5,1,Forward,Ratecard 1,0.5,0.5,Forward,Base,₹ 20,₹ 24,₹ 35,₹ 36,₹ 45
200,96467,Delhivery Surface,A,0.7500,0.5,1,Forward,Ratecard 1,0.5,0.5,Forward,Additional .5 kg,₹ 15,₹ 18,₹ 28,₹ 29,₹ 36
201,96467,Delhivery Surface,A,0.7500,0.5,1,Forward,Ratecard 1,0.5,0.5,Return,Base,₹ 16.15,₹ 18.70,₹ 29.17,₹ 30.18,₹ 36.59
202,96467,Delhivery Surface,A,0.7500,0.5,1,Forward,Ratecard 1,0.5,0.5,Return,Additional .5 kg,₹ 15.30,₹ 17.85,₹ 28.32,₹ 29.33,₹ 35.74

In [90]:
# Calculate the total shipping cost by multiplying "Charged wt" with "Multiplier" and "Additional"
merged_data['Total Cost'] = merged_data['Charged wt'] * merged_data['Multiplier'] * merged_data['Additional']
merged_data

,AWB,Courier,Zone,Charged wt,Courier Slab,Multiplier,Direction,RateCard,Weight Slab,Additional,Ratecard 1,Freight Type,A,B,C,D,E,Total Cost
0,96403,Delhivery Surface 10 Kgs,A,10.5000,10.0,1,Forward,Ratecard 1,10.0,1.0,Forward,Base,₹ 128,₹ 148,₹ 207,₹ 255,₹ 297,10.500
1,96403,Delhivery Surface 10 Kgs,A,10.5000,10.0,1,Forward,Ratecard 1,10.0,1.0,Forward,Additional 1 kg,₹ 11,₹ 13,₹ 18,₹ 22,₹ 26,10.500
2,96403,Delhivery Surface 10 Kgs,A,10.5000,10.0,1,Forward,Ratecard 1,10.0,1.0,Return,Base,₹ 89.25,₹ 103.88,₹ 145.22,₹ 178.50,₹ 207.75,10.500
3,96403,Delhivery Surface 10 Kgs,A,10.5000,10.0,1,Forward,Ratecard 1,10.0,1.0,Return,Additional 1 kg,₹ 11.08,₹ 12.90,₹ 18.05,₹ 22.18,₹ 25.81,10.500
4,96404,Shipsy,A,0.5475,0.5,1,Forward,Ratecard 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198,96466,Shipsy,A,5.1750,0.5,10,Forward,Ratecard 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199,96467,Delhivery Surface,A,0.7500,0.5,1,Forward,Ratecard 1,0.5,0.5,Forward,Base,₹ 20,₹ 24,₹ 35,₹ 36,₹ 45,0.375
200,96467,Delhivery Surface,A,0.7500,0.5,1,Forward,Ratecard 1,0.5,0.5,Forward,Additional .5 kg,₹ 15,₹ 18,₹ 28,₹ 29,₹ 36,0.375
201,96467,Delhivery Surface,A,0.7500,0.5,1,Forward,Ratecard 1,0.5,0.5,Return,Base,₹ 16.15,₹ 18.70,₹ 29.17,₹ 30.18,₹ 36.59,0.375
202,96467,Delhivery Surface,A,0.7500,0.5,1,Forward,Ratecard 1,0.5,0.5,Return,Additional .5 kg,₹ 15.30,₹ 17.85,₹ 28.32,₹ 29.33,₹ 35.74,0.375

In [91]:
# Group by "Zone" and calculate the average shipping cost
average_cost_by_zone = merged_data.groupby('Zone')['Total Cost'].mean()

In [92]:
print(average_cost_by_zone)

Zone
A     12.958594
B     36.112500
C    133.700000
D     78.694615
E      4.590000
Name: Total Cost, dtype: float64

In [94]:
a = data1[(data1['Direction'] == 'Forward') & (data1['Courier'] == 'Delhivery Surface 10 Kgs') & (data1['Zone'] == 'A')].reset_index(drop=True)

In [95]:
a['Price'] = 128

In [96]:
a['Multiplier'].apply(lambda x: 11+128 if x == 1 else 128)

0    139
1    139
2    128
Name: Multiplier, dtype: int64

In [97]:
a

,AWB,Courier,Zone,Charged wt,Courier Slab,Multiplier,Direction,Price
0,96403,Delhivery Surface 10 Kgs,A,10.5,10.0,1,Forward,128
1,96406,Delhivery Surface 10 Kgs,A,10.5,10.0,1,Forward,128
2,96437,Delhivery Surface 10 Kgs,A,12.0,10.0,2,Forward,128

In [98]:
l = []
for i in a['Multiplier']:
    c = abs(0-i)
    print(c)
    pr = c*11
    l.append(128+pr)
    
a['M_price'] = l

1
1
2

In [99]:
data3

,Ratecard 1,Weight Slab,Freight Type,A,B,C,D,E
0,Forward,0.5,Base,₹ 20,₹ 24,₹ 35,₹ 36,₹ 45
1,Forward,0.5,Additional .5 kg,₹ 15,₹ 18,₹ 28,₹ 29,₹ 36
2,Forward,2.0,Base,₹ 48,₹ 63,₹ 74,₹ 90,₹ 111
3,Forward,2.0,Additional 1 kg,₹ 20,₹ 29,₹ 34,₹ 40,₹ 49
4,Forward,5.0,Base,₹ 97,₹ 112,₹ 121,₹ 130,₹ 161
5,Forward,5.0,Additional 1 kg,₹ 17,₹ 21,₹ 23,₹ 24,₹ 29
6,Forward,10.0,Base,₹ 128,₹ 148,₹ 207,₹ 255,₹ 297
7,Forward,10.0,Additional 1 kg,₹ 11,₹ 13,₹ 18,₹ 22,₹ 26
8,Return,0.5,Base,₹ 16.15,₹ 18.70,₹ 29.17,₹ 30.18,₹ 36.59
9,Return,0.5,Additional .5 kg,₹ 15.30,₹ 17.85,₹ 28.32,₹ 29.33,₹ 35.74
10,Return,2.0,Base,₹ 33.28,₹ 44.38,₹ 51.94,₹ 63.03,₹ 77.66
11,Return,2.0,Additional 1 kg,₹ 20.24,₹ 28.82,₹ 33.96,₹ 40.48,₹ 49.39
12,Return,5.0,Base,₹ 68.09,₹ 78.43,₹ 84.72,₹ 91.26,₹ 112.86
13,Return,5.0,Additional 1 kg,₹ 17.19,₹ 20.89,₹ 22.75,₹ 24.34,₹ 29.31
14,Return,10.0,Base,₹ 89.25,₹ 103.88,₹ 145.22,₹ 178.50,₹ 207.75
15,Return,10.0,Additional 1 kg,₹ 11.08,₹ 12.90,₹ 18.05,₹ 22.18,₹ 25.81

In [114]:
dummy = data1.copy()

dummy['m_price'] = 0

for d in range(len(dummy)):
    if dummy['Courier'][d] == 'Delhivery Surface 10 Kgs':
        if dummy['Zone'][d] == 'A':
            if dummy['Direction'][d] == 'Forward':
                i = dummy['Multiplier'][d]
                c = abs(0-i)
                pr = c*11
                m_price = 128+pr
                dummy['m_price'][d] = m_price
            if dummy['Direction'][d] == 'Return':
                i = dummy['Multiplier'][d]
                c = abs(0-i)
                pr = c*11.06
                m_price = 89.25+pr
                dummy['m_price'][d] = m_price
        if dummy['Zone'][d] == 'B':
            if dummy['Direction'][d] == 'Forward':
                i = dummy['Multiplier'][d]
                c = abs(0-i)
                pr = c*13
                m_price = 148+pr
                dummy['m_price'][d] = m_price
            if dummy['Direction'][d] == 'Return':
                i = dummy['Multiplier'][d]
                c = abs(0-i)
                pr = c*12.90
                m_price = 103.88+pr
                dummy['m_price'][d] = m_price
        if dummy['Zone'][d] == 'C':
            if dummy['Direction'][d] == 'Forward':
                i = dummy['Multiplier'][d]
                c = abs(0-i)
                pr = c*18
                m_price = 207+pr
                dummy['m_price'][d] = m_price
            if dummy['Direction'][d] == 'Return':
                i = dummy['Multiplier'][d]
                c = abs(0-i)
                pr = c*18.05
                m_price = 145.22+pr
                dummy['m_price'][d] = m_price
        if dummy['Zone'][d] == 'D':
            if dummy['Direction'][d] == 'Forward':
                i = dummy['Multiplier'][d]
                c = abs(0-i)
                pr = c*22
                m_price = 255*pr
                dummy['m_price'][d] = m_price
            if dummy['Direction'][d] == 'Return':
                i = dummy['Multiplier'][d]
                c = abs(0-i)
                pr = c*22.18
                m_price = 178.50+pr
                dummy['m_price'][d] = m_price
        if dummy['Zone'][d] == 'E':
            if dummy['Direction'][d] == 'Forward':
                i = dummy['Multiplier'][d]
                c = abs(0-i)
                pr = c*26
                m_price = 297+pr
                dummy['m_price'][d] = m_price
            if dummy['Direction'][d] == 'Return':
                i = dummy['Multiplier'][d]
                c = abs(0-i)
                pr = c*25.81
                m_price = 207.75+pr
                dummy['m_price'][d] = m_price
                    
    if dummy['Courier'][d] == 'Shipsy':
        dummy['m_price'][d] = 150
    
    if dummy['Courier'][d] == 'Delhivery Surface 5 Kgs':
        if dummy['Zone'][d] == 'A':
            if dummy['Direction'][d] == 'Forward':
                i = dummy['Multiplier'][d]
                c = abs(0-i)
                pr = c*17
                m_price = 97+pr
                dummy['m_price'][d] = m_price
            if dummy['Direction'][d] == 'Return':
                i = dummy['Multiplier'][d]
                c = abs(0-i)
                pr = c*17.19
                m_price = 68.09+pr
                dummy['m_price'][d] = m_price
        if dummy['Zone'][d] == 'B':
            if dummy['Direction'][d] == 'Forward':
                i = dummy['Multiplier'][d]
                c = abs(0-i)
                pr = c*21
                m_price = 112+pr
                dummy['m_price'][d] = m_price
            if dummy['Direction'][d] == 'Return':
                i = dummy['Multiplier'][d]
                c = abs(0-i)
                pr = c*20.89
                m_price = 78.43+pr
                dummy['m_price'][d] = m_price
        if dummy['Zone'][d] == 'C':
            if dummy['Direction'][d] == 'Forward':
                i = dummy['Multiplier'][d]
                c = abs(0-i)
                pr = c*23
                m_price = 121+pr
                dummy['m_price'][d] = m_price
            if dummy['Direction'][d] == 'Return':
                i = dummy['Multiplier'][d]
                c = abs(0-i)
                pr = c*22.75
                m_price = 84.72+pr
                dummy['m_price'][d] = m_price
        if dummy['Zone'][d] == 'D':
            if dummy['Direction'][d] == 'Forward':
                i = dummy['Multiplier'][d]
                c = abs(0-i)
                pr = c*24
                m_price = 130*pr
                dummy['m_price'][d] = m_price
            if dummy['Direction'][d] == 'Return':
                i = dummy['Multiplier'][d]
                c = abs(0-i)
                pr = c*24.34
                m_price = 91.26+pr
                dummy['m_price'][d] = m_price
        if dummy['Zone'][d] == 'E':
            if dummy['Direction'][d] == 'Forward':
                i = dummy['Multiplier'][d]
                c = abs(0-i)
                pr = c*29
                m_price = 161+pr
                dummy['m_price'][d] = m_price
            if dummy['Direction'][d] == 'Return':
                i = dummy['Multiplier'][d]
                c = abs(0-i)
                pr = c*29.31
                m_price = 112.86+pr
                dummy['m_price'][d] = m_price
    if dummy['Courier'][d] == 'Delhivery Surface 2 Kgs' or 'Xpressbees 2kg':
        if dummy['Zone'][d] == 'A':
            if dummy['Direction'][d] == 'Forward':
                i = dummy['Multiplier'][d]
                c = abs(0-i)
                pr = c*20
                m_price = 48+pr
                dummy['m_price'][d] = m_price
            if dummy['Direction'][d] == 'Return':
                i = dummy['Multiplier'][d]
                c = abs(0-i)
                pr = c*20.24
                m_price = 33.28+pr
                dummy['m_price'][d] = m_price
        if dummy['Zone'][d] == 'B':
            if dummy['Direction'][d] == 'Forward':
                i = dummy['Multiplier'][d]
                c = abs(0-i)
                pr = c*29
                m_price = 63+pr
                dummy['m_price'][d] = m_price
            if dummy['Direction'][d] == 'Return':
                i = dummy['Multiplier'][d]
                c = abs(0-i)
                pr = c*28.82
                m_price = 44.38+pr
                dummy['m_price'][d] = m_price
        if dummy['Zone'][d] == 'C':
            if dummy['Direction'][d] == 'Forward':
                i = dummy['Multiplier'][d]
                c = abs(0-i)
                pr = c*34
                m_price = 74+pr
                dummy['m_price'][d] = m_price
            if dummy['Direction'][d] == 'Return':
                i = dummy['Multiplier'][d]
                c = abs(0-i)
                pr = c*33.96
                m_price = 51.94+pr
                dummy['m_price'][d] = m_price
        if dummy['Zone'][d] == 'D':
            if dummy['Direction'][d] == 'Forward':
                i = dummy['Multiplier'][d]
                c = abs(0-i)
                pr = c*40
                m_price = 90*pr
                dummy['m_price'][d] = m_price
            if dummy['Direction'][d] == 'Return':
                i = dummy['Multiplier'][d]
                c = abs(0-i)
                pr = c*40.48
                m_price = 63.03+pr
                dummy['m_price'][d] = m_price
        if dummy['Zone'][d] == 'E':
            if dummy['Direction'][d] == 'Forward':
                i = dummy['Multiplier'][d]
                c = abs(0-i)
                pr = c*49
                m_price = 111+pr
                dummy['m_price'][d] = m_price
            if dummy['Direction'][d] == 'Return':
                i = dummy['Multiplier'][d]
                c = abs(0-i)
                pr = c*49.39
                m_price = 77.66+pr
                dummy['m_price'][d] = m_price
    if dummy['Courier'][d] == 'Delhivery Surface' or 'Blue Dart' or 'XPRESSBEES':
        if dummy['Zone'][d] == 'A':
            if dummy['Direction'][d] == 'Forward':
                i = dummy['Multiplier'][d]
                c = abs(0-i)
                pr = c*15
                m_price = 20+pr
                dummy['m_price'][d] = m_price
            if dummy['Direction'][d] == 'Return':
                i = dummy['Multiplier'][d]
                c = abs(0-i)
                pr = c*15.30
                m_price = 16.15+pr
                dummy['m_price'][d] = m_price
        if dummy['Zone'][d] == 'B':
            if dummy['Direction'][d] == 'Forward':
                i = dummy['Multiplier'][d]
                c = abs(0-i)
                pr = c*18
                m_price = 24+pr
                dummy['m_price'][d] = m_price
            if dummy['Direction'][d] == 'Return':
                i = dummy['Multiplier'][d]
                c = abs(0-i)
                pr = c*17.85
                m_price = 18.70+pr
                dummy['m_price'][d] = m_price
        if dummy['Zone'][d] == 'C':
            if dummy['Direction'][d] == 'Forward':
                i = dummy['Multiplier'][d]
                c = abs(0-i)
                pr = c*28
                m_price = 35+pr
                dummy['m_price'][d] = m_price
            if dummy['Direction'][d] == 'Return':
                i = dummy['Multiplier'][d]
                c = abs(0-i)
                pr = c*28.32
                m_price = 29.17+pr
                dummy['m_price'][d] = m_price
        if dummy['Zone'][d] == 'D':
            if dummy['Direction'][d] == 'Forward':
                i = dummy['Multiplier'][d]
                c = abs(0-i)
                pr = c*29
                m_price = 36*pr
                dummy['m_price'][d] = m_price
            if dummy['Direction'][d] == 'Return':
                i = dummy['Multiplier'][d]
                c = abs(0-i)
                pr = c*29.33
                m_price = 30.18+pr
                dummy['m_price'][d] = m_price
        if dummy['Zone'][d] == 'E':
            if dummy['Direction'][d] == 'Forward':
                i = dummy['Multiplier'][d]
                c = abs(0-i)
                pr = c*36
                m_price = 45+pr
                dummy['m_price'][d] = m_price
            if dummy['Direction'][d] == 'Return':
                i = dummy['Multiplier'][d]
                c = abs(0-i)
                pr = c*35.74
                m_price = 36.59+pr
                dummy['m_price'][d] = m_price

In [115]:
dummy.groupby(['Zone','Courier'])['m_price'].mean()

Zone  Courier
A     Blue Dart                      31.250000
      Delhivery Surface              31.250000
      Delhivery Surface 10 Kgs       40.000000
      Delhivery Surface 5 Kgs        80.000000
      Shipsy                        197.631579
      Xpressbees 2kg                 65.000000
B     Blue Dart                      36.000000
      Delhivery Surface              24.000000
      Delhivery Surface 10 Kgs      240.000000
      Delhivery Surface 5 Kgs        60.000000
      Xpressbees 2kg                 46.500000
C     Blue Dart                      91.000000
      Delhivery Surface 10 Kgs       77.000000
      Delhivery Surface 2 Kgs       119.000000
      Delhivery Surface 5 Kgs       735.000000
D     Blue Dart                    1955.714286
      Delhivery Surface 10 Kgs     5220.000000
      Delhivery Surface 2 Kgs      4176.000000
      Delhivery Surface 5 Kgs     11484.000000
E     XPRESSBEES                     45.000000
      Xpressbees 2kg                 99.000000
Name: m_price, dtype: float64